# Generated by Django 3.0.8 on 2020-07-02 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ghostpost_roast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghostpost',
            name='roast',
        ),
    ]
