# Generated by Django 3.0.8 on 2020-07-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ghostpost_roast'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghostpost',
            name='roast',
            field=models.BooleanField(default=False),
        ),
    ]
